# fly.toml app configuration file generated for openborys on 2026-04-25T23:22:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openborys'
primary_region = 'fra'

[build]

[deploy]
  strategy = "immediate"
  max_unavailable = 1

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
