#!/usr/bin/env bash
# Run to generate .env.local
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <bot>" >&2
  exit 1
fi

bot="$1"
bot_env=".env.$bot"

for f in .env.shared "$bot_env"; do
  if [[ ! -f "$f" ]]; then
    echo "missing $f" >&2
    exit 1
  fi
done

{
  echo "# Generated by scripts/use.sh from .env.shared + $bot_env. Do not edit."
  cat .env.shared "$bot_env"
} > .env.local

echo "local env now: $bot"
